### ISSUE TITLE
respec2html.js race condition: Target closed

### ISSUE THREAD

**Issue by nickevansuk** [w3c/respec#2477]
## Important info

* URL to affected spec: https://www.openactive.io/modelling-opportunity-data/EditorsDraft/edit.html
* ReSpec version: Click the ReSpec pill (e.g., 24.30.4).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

`respec2html "file://$PWD/EditorsDraft/edit.html" "$PWD/out/EditorsDraft/index.html" "EditorsDraft"`

Produces the error:

```
(node:30315) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/puppeteer/lib/helper.js:112:23)
    at stringifyJSHandle (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/respec/tools/respecDocWriter.js:262:42)
    at Array.map (<anonymous>)
    at Page.page.on (/Users/nick/repos/openactive/modelling-opportunity-data/node_modules/respec/tools/respecDocWriter.js:227:53)
    at Page.emit (events.js:198:13)
```

The above should instead read:
```
🚨 ReSpec warning: Linter (local-refs-exist): Broken local reference found in document. Please fix the links mentioned. See developer console. Occured at: [1](#respec-offender-linter-local-refs-exist-broken-local-reference-found-in-document-please-fix-the-links-mentioned-see-developer-console-occured), [2](#respec-offender-linter-local-refs-exist-broken-local-reference-found-in-document-please-fix-the-links-mentioned-see-developer-console-occured-0).
🚨 ReSpec warning: Linter (local-refs-exist): Broken local reference found in document. Please fix the links mentioned. See developer console. Occured file:///Users/nick/repos/openactive/modelling-opportunity-data/EditorsDraft/edit.html#,file:///Users/nick/repos/openactive/modelling-opportunity-data/EditorsDraft/edit.html#describing-route-metadata-oa-routemetadata-
```

## Diagnosis

This appears to be a race condition caused by the browser being closed (https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js#L110) before the console log statements have been processed using `stringifyJSHandle` https://github.com/w3c/respec/blob/develop/tools/respecDocWriter.js#L259.

## Solution

At a quick glance there doesn't seem to be an easy way to wait for the browser to finish processing all events, so a quick fix would be to add a 1s wait (see https://github.com/w3c/respec/pull/2478). This fixes the problem.

**Comment by sidvishnoi** [comment]
Fixed via https://github.com/w3c/respec/pull/2478
