### ISSUE TITLE
Getting error when generating using labs

### ISSUE THREAD

**Issue by jnurthen** [w3c/respec#3699]
## Important info

- URL to affected spec: https://github.com/w3c/dpub-aam
- ReSpec version: Click the ReSpec pill in top-right corner (e.g., 25.12.0).
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

**What happened (e.g., it crashed)?:**
Got error:
{"error":"\n😭  Sorry, there was an error generating the HTML. Please report this issue!\nSpecification: https://raw.githack.com/w3c/dpub-aam/main/index.html?publishDate=2021-07-21\nReSpec version: 25.6.0\nFile a bug: https://github.com/w3c/respec/\nError: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 28725ms.\n    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:276:12)\n    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)\n    at async Object.generate [as respec] (/u/spec-generator/generators/respec.js:14:44)\n    at async /u/spec-generator/server.js:203:44\n"}
**Expected behavior (e.g., it shouldn't crash):**
Should work
**Optional, steps to reproduce:**
Run https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/dpub-aam/main/index.html
1

**Comment by jnurthen** [comment]
This works locally with no errors

**Comment by marcoscaceres** [comment]
Hi @jnurthen, 

The document at:
https://raw.githack.com/w3c/dpub-aam/main/index.html

Is throwing errors:
"ReferenceError: Can't find variable: respecConfig"

Which I think is causing it to fail. 

That's failing because the "biblio" hasn't been loaded and created yet.

**Comment by marcoscaceres** [comment]
Yeah, the bug is because biblio.js is not creating a "`var biblio`". it's trying to create `respecConfig.localBiblio = {}`, which doesn't exist yet.
