### ISSUE TITLE
Flaky timeout within Github Action run

### ISSUE THREAD

**Issue by jyasskin** [w3c/respec#3977]
## Important info

- ReSpec version: 28.2.8
- [x] I did a "hard refresh", but it's still busted.

## Description of problem

https://github.com/w3ctag/privacy-principles/actions/runs/1757759244/attempts/1 failed with

```
    $ respec -s "http://localhost:3000/index.html" -o "index.html.built.html" --verbose -t 20 -w
      [INFO] [Timeout: 20000ms] Processing resource: http://localhost:3000/index.html ...
      [INFO] [Timeout: 19995ms] Launching browser
      [INFO] [Timeout: 4601ms] Navigating to http://localhost:3000/index.html
      [INFO] [Timeout: 907ms] Navigation complete.
      [INFO] [Timeout: 467ms] Using ReSpec v28.2.8
      [INFO] [Timeout: 467ms] Processing ReSpec document...
      [FATAL] Error: 
      😭  Sorry, there was an error generating the HTML. Please report this issue!
      Specification: http://localhost:3000/index.html
      ReSpec version: 28.2.8
      File a bug: https://github.com/w3c/respec/
      Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 466ms.
          at ExecutionContext._evaluateInternal (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async ExecutionContext.evaluate (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
          at async generateHTML (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respecDocWriter.js:221:12)
          at async toHTML (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respecDocWriter.js:92:18)
          at async run (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respec2html.js:228:38)
      
          at generateHTML (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respecDocWriter.js:228:11)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async toHTML (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respecDocWriter.js:92:18)
          at async run (/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/respec/tools/respec2html.js:228:38)
    Failed
```

The retry succeeded. Then https://github.com/w3ctag/privacy-principles/runs/4971744503?check_suite_focus=true failed with the same error.

**Comment by marcoscaceres** [comment]
Thanks! Yeah, we have also been seeing this CI :( I'm not sure if one of the server we rely on is being slow or if we forgot to `await` a promise somewhere. I'll do some more investigating this week. Sorry for the annoyance!

**Comment by marcoscaceres** [comment]
Closing as works for me
